# 数据参数
train_dir: "processed_data_0322/train"
val_dir: "processed_data_0322/test"
window_size: 120
stride: 30
normalize_imu: true
mode: "train"

# 训练参数
batch_size: 256
num_epochs: 100
lr: 0.0001
weight_decay: 0.00001
grad_clip: 1.0
seed: 42
num_workers: 4

# 模型参数
hidden_dim: 512
num_layers: 6
nhead: 6
dropout: 0.1
diffusion_steps: 1000
bps_n_points: 1024
use_object: false

# 输出参数
output_dir: "output"
save_interval: 10 