# TransPose模型训练配置文件

# 基本配置
model_name: "TransPose_IMU"
tensorboard_project_name: "imu_transpose"  # TensorBoard项目名称
model_type: "TransPose"  # 模型类型：使用TransPose
device: "cuda:0"  # 主GPU设备
gpus: [0]  # 使用的GPU编号列表，支持多卡训练
           # 单卡训练: [0] 
           # 双卡训练: [0, 1]
save_dir: "outputs/TransPose"  # 模型保存路径
use_tensorboard: True  # 是否使用tensorboard记录训练过程
use_multi_gpu: True  # 是否启用多GPU训练（当gpus列表长度>1时自动启用）
# pretrained_checkpoint: "checkpoints/TransPose/epoch_50_best.pt"  # 预训练模型路径，如果需要从现有模型继续训练，取消注释并设置路径
bm_path: body_models/smplh/male/model.npz
use_transpose_model: True

# 训练超参数
epoch: 850  # 训练轮数
batch_size: 2  # 批大小（多GPU时会自动分配到各GPU）
lr: 0.0004  # 学习率（多GPU时会自动按GPU数量线性缩放）
weight_decay: 0.0001  # 权重衰减
milestones: [300, 500, 700, 800]  # 学习率调整节点
gamma: 0.2  # 学习率衰减系数
seed: 42  # 随机种子
num_workers: 12  # 数据加载线程数（多GPU时建议增加）
hidden_dim_multiplier: 1  # 隐藏层维度乘数

# 特征维度配置
num_human_imus: 6  # 人体IMU数量
imu_dim: 9  # 每个IMU的特征维度（加速度向量3维 + 6D旋转表示6维）
num_joints: 22  # SMPL模型关节数量
joint_dim: 6  # 使用6D旋转表示
vel_scale: 3

# 物体静止相关参数
obj_imu_change_threshold: 0.1
obj_contact_threshold: 0.3
obj_rot_weight: 0.5

# ContactAwareLoss相关参数
use_contact_aware_loss: False  # 是否使用ContactAwareLoss
contact_distance: 0.1  # 目标接触距离 10cm
contact_ramp_up_steps: 10000  # 基础损失3000步后达到全权重

# ContactAwareLoss内部权重
contact_loss_weights:
  contact_distance: 1.0      # 距离一致性权重
  contact_velocity: 0.5      # 速度一致性权重
  approach_smoothness: 0.3   # 接近平滑性权重
  contact_consistency: 0.2   # 接触状态一致性权重

# 手部接触相关参数
hand_contact_distance: 0.1   # 10cm目标距离

# 分阶段训练配置
staged_training:
  enabled: True  # 是否启用分阶段训练
  
  # 模块化训练配置
  modular_training:
    enabled: True  # 是否启用模块化训练
    start_from_stage: "joint_training"  # 从哪个阶段开始训练，可选: "velocity_contact", "human_pose", "object_trans", "joint_training"
    pretrained_modules:  # 预训练模块路径
      velocity_contact: "outputs/TransPose/transpose_07171644/modules/velocity_contact_best.pt"
      human_pose: "outputs/TransPose/transpose_07171644/modules/human_pose_best.pt"
      object_trans: "outputs/TransPose/transpose_07171644/modules/object_trans_best.pt"
  
  stages:
  - name: "velocity_contact"
    epochs: [0, 10]  # epoch范围：0-49 (共50个epoch)
    modules: ["velocity_contact"]  # 激活的模块
    datasets: ["omomo"]  # 使用的数据集类型：amass、omomo、mixed
  - name: "human_pose_omomo"  
    epochs: [11, 20]  # epoch范围：150-199 (共50个epoch) - 再用OMOMO微调
    modules: ["human_pose"]  # 激活的模块
    datasets: ["omomo"]  # 只使用OMOMO数据集
  - name: "object_trans"
    epochs: [21, 30]  # epoch范围：200-249 (共50个epoch)
    modules: ["object_trans"]  # 激活的模块
    datasets: ["omomo"]  # 只使用OMOMO数据集（有物体）
  - name: "joint_training"
    epochs: [31, 40]  # epoch范围：250-399 (共150个epoch)
    modules: ["human_pose", "object_trans"]  # 激活的模块
    datasets: ["omomo"]  # 只使用OMOMO数据集（有物体）


# 数据集配置
datasets:
  amass:
    train_path: "processed_amass_data_0703/train"
    test_path: "processed_amass_data_0703/test"
    debug_path: "processed_amass_data_0703/debug"  # AMASS调试数据路径
  omomo:
    train_path: "processed_data_0701/debug"
    test_path: "processed_data_0701/debug"
    debug_path: "processed_data_0701/debug"  # OMOMO调试数据路径

# 损失权重配置
loss_weights:
  rot: 10  # 姿态损失权重
  root_pos: 10  # 根节点位置损失权重
  obj_trans: 5  # 物体位置损失权重
  obj_relative_trans: 10  # 物体相对位置损失权重
  obj_rot: 1.0  # 物体旋转损失权重
  leaf_pos: 1.0  # 叶子节点位置损失权重
  full_pos: 1.0  # 全身关节位置损失权重
  root_vel: 10  # 根关节速度损失权重
  tran_b2: 0.001  # 根关节速度损失权重
  hand_contact: 1  # 手部接触损失权重
  contact_aware: 1.0  # 接触感知损失权重
  obj_vel: 1  # 物体速度损失权重
  leaf_vel: 10  # 叶子节点速度损失权重
  foot_contact: 1  # 足部接触损失权重
  lhand_obj_pose: 5  # 左手物体姿态损失权重
  rhand_obj_pose: 5  # 右手物体姿态损失权重
  obj_trans_from_pose: 8  # 根据姿态计算的物体位置损失权重
  lhand_bone_length: 1  # 左手虚拟骨长损失权重（新增）
  rhand_bone_length: 1  # 右手虚拟骨长损失权重（新增）

# 训练窗口配置
train:
  window: 120  # 训练时使用的时间窗口长度
  # window_stride: 60  # 训练时窗口步长
  normalize: True  # 是否归一化数据
  data_path: 
    "processed_data_0701/train"  # 训练数据路径1（传统模式使用）
  debug_data_path: "processed_data_0701/debug"  # 调试数据路径

# 测试窗口配置
test:
  window: 120  # 测试时使用的时间窗口长度
  # window_stride: 120  # 测试时窗口步长
  normalize: True  # 是否归一化数据
  data_path: 
    "processed_data_0701/test"  # 测试数据路径1（传统模式使用）

# 数据增强配置
augmentation:
  use_augmentation: True  # 是否使用数据增强
  rotation_augmentation: True  # 是否使用旋转增强
  noise_augmentation: True  # 是否使用噪声增强
  noise_std: 0.01  # 噪声标准差 

# 噪声参数配置
noise_params:
  init_rotation_noise_std: 0.1  # 初始旋转矩阵噪声标准差
  bone_length_noise_std: 0.05   # 骨长噪声标准差 